inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['\A#*']

Metrics/MethodLength:
  Max: 20

Style/ClassCheck:
  EnforcedStyle: is_a?

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Style/StringLiterals:
  EnforcedStyle: double_quotes
